### PR TITLE
Support aemanalyser-maven-plugin in the generated projects (#533)

### PR DESCRIPTION
**Pull request by bosschaert**
Note this is a draft PR. To see if my changes are acceptable or if anything should be changed.

## Description

AEMaaCS provides extended analysis of projects in the build and deployment pipeline. This includes running the Feature Model Analysers on the content packages. If these analysers find a problem they will fail the build and the developer needs to rectify the problem. 
This can be problematic for developers as there is an amount of time between these failures in the deployment pipelines and the actual development of the content packages.

The new [aemanalyser-maven-plugin](https://github.com/adobe/aemanalyser-maven-plugin/blob/main/aemanalyser-maven-plugin/README.md) makes it possible to run these analysers that are already running in the pipeline on the developer's local machine as part of the Maven build. This will give much quicker feedback to the developer and shortens the developer life cycle.
Note: the aemanalyser-maven-plugin currently under development, this draft PR refers to a SNAPSHOT version of it, we need to get that plugin released before we can use it from this archetype (hence the draft PR).

## Motivation and Context

Shorten the development lifecycle and provide early feedback.

## How Has This Been Tested?

It has been tested by running the following commandline on my branch:

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=25-SNAPSHOT \
 -D appTitle="Test1" \
 -D appId="test1" \
 -D groupId="com.mysite
```

And then running `mvn install` to see if the analysis is triggered.

The changes to the archetype introduce a new module which sole purpose is to run the analysis. There are no changes needed to the other projects, just an extra dependency and an extra module referenced in the top level pom. 

If everything is good then the build will just complete for the developer as before. If the analysers find issues then the build of the new `analyse` module will fail.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by bosschaert** [comment]
The tests are failing because this draft PR still references a SNAPSHOT Maven plugin. As mentioned in the description I filed it to gather some feedback 😄

**Comment by kwin** [comment]
Is there a requirement that the plugin is compiled with Java 11? Otherwise please make it available for Java 8 Maven builds as well.

**Comment by bosschaert** [comment]
@kwin good point - there was no real requirement for Java 11, so I moved it back to Java 8 for the aemanalyser-maven-plugin.

**Comment by kwin** [comment]
What is the reason the plugin cannot be included in the `all` module and requires a dedicated module instead?

**Comment by bosschaert** [comment]
Closing for now while I continue to work on this...

**Comment by bosschaert** [comment]
> What is the reason the plugin cannot be included in the `all` module and requires a dedicated module instead?

That should also be possible. To a certain degree it's a matter of taste IMHO. Having it in a separate module folllows a pattern similar to integration tests which are often in separate modules. It's the least intrusive as it doesn't require existing modules to change. But yes, both are possible.

**Pull request closed without merging**
