### PR TITLE
CQ-4309697 - Add OOTB themes to AEM Project Archetype

### PR DESCRIPTION
**Pull request by pankaj-parashar**
Addition of new ootb AEM Forms themes

## Description

Adding the following themes.
Tranquil
Urbane
Beryl
Ultramarine

## Motivation and Context

Providing more ootb themes

## How Has This Been Tested?

Manual testing by creating archetype project locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by pankaj-parashar** [comment]
@sakshi-arora1, @rismehta  please review this. I am manually testing this, will push changes further for any issues found. Please focus on reviewing theme content nodes, clientlibs under /apps. Fonts has been picked as is from the internal repo.

**Review by sakshi-arora1 — COMMENTED** [review]
Clientlibs like:
```
 ...in/content/jcr_root/apps/__appId__/clientlibs/clientlibs-forms/urbane-style
oot/apps/__appId__/clientlibs/clientlibs-forms/us-web-design-standards-style/
...ntent/jcr_root/apps/__appId__/clientlibs/clientlibs-forms/ultramarine-style/
```
should be clubbed under one like clientlibs-forms/theme_base/...

Also can you see we are only checking in those fonts which are actually being utilised in the added themes.

I have just reviewed the structure of the added files, not the content...

**Comment by pankaj-parashar** [comment]
> Clientlibs like:
> 
> ```
>  ...in/content/jcr_root/apps/__appId__/clientlibs/clientlibs-forms/urbane-style
> oot/apps/__appId__/clientlibs/clientlibs-forms/us-web-design-standards-style/
> ...ntent/jcr_root/apps/__appId__/clientlibs/clientlibs-forms/ultramarine-style/
> ```
> 
> should be clubbed under one like clientlibs-forms/theme_base/...
> 
> Also can you see we are only checking in those fonts which are actually being utilised in the added themes.
> 
> I have just reviewed the structure of the added files, not the content...

@sakshi-arora1 , this has been fixed.

**Comment by pankaj-parashar** [comment]
@sakshi-arora1 , @rismehta please re-review this PR. The following changes have been done.

1. Theme base client lib restructured
2. Fonts usage checked, only used font-families included. Restructured the fonts client lib, now fonts are residing under resources folder.
3. Few theme specific style issues fixed

**Comment by pankaj-parashar** [comment]
Recent Changes.

1. Only Source Sans Pro fonts being used. Removed Open Sans fonts.
2. Radio button and checkbox Item large label going off screen issue fixed for all themes.

@sakshi-arora1 , please re-review this pr for ootb theme content. For Testing these themes another PR will be raised.soon.

**Comment by sakshi-arora1** [comment]
Structurally its correct. Approving it.
cc: @pankaj-parashar

**Review by sakshi-arora1 — APPROVED** [review]

**Review by rismehta — APPROVED** [review]
Approving as @sakshi-arora1 has reviewed it. 
@pankaj-parashar  When are we planning to add test cases for this change ?

**Comment by rismehta** [comment]
Test cases for these changes are tracked separately via, https://github.com/adobe/aem-project-archetype/pull/802/files. Merging this.

**Pull request merged**
