### PR TITLE
removed 6.3 references, updated 6.4 and 6.5 Service Packs

### LINKED ISSUE #349: Update supported AEM versions
* Remove 6.3
* Update 6.4 and 6.5 to latest SPs
* Make `cloud` the default AEM version

### PR DESCRIPTION
**Pull request by msagolj**
## Description
- Removed 6.3 related dependencies, statements, ifs etc.
- only 6.4.8 and 6.5.5 can be set as onprem AEM versions
- adapted test projects to new version number

NOTE: The README.md and VERSIONS.md will be updated at time of release 24 (#493 )

## Related Issue
Fixes #349 

## How Has This Been Tested?
- Local build with all test scenarios
- generate/build/deploy projects to AEM

### CODE REVIEW

**Comment by kwin** [comment]
Does 6.4.8 really ship with Installer Configuration Factory 1.2.0+ (for https://issues.apache.org/jira/browse/SLING-7786 and https://issues.apache.org/jira/browse/SLING-7787)?

**Comment by msagolj** [comment]
> Does 6.4.8 really ship with Installer Configuration Factory 1.2.0+ (for https://issues.apache.org/jira/browse/SLING-7786 and https://issues.apache.org/jira/browse/SLING-7787)?

I guess that in reference to #454  : Provided OSGi configuration factories using use ~ instead of - in filename
You are right , latest 6.4.8.2 only provides 1.1.3.B001.

Will extend this PR with a fix.

**Comment by kwin** [comment]
This won't work with cfg.json files within src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig either.

**Comment by msagolj** [comment]
@kwin so i have to bring back the old xml configs that where deleted in:
 https://github.com/adobe/aem-project-archetype/pull/476/files#diff-b3a5be2295b22ab13ca6f5388fe6bfe0

correct ?

**Comment by kwin** [comment]
As outlined in https://sling.apache.org/documentation/bundles/configuration-installer-factory.html. 
Best is `.cfg.json`. Second best is `.config`. Worst is `sling:OsgiConfig` due to all the limitations. So if you want to support AEM 6.4 I would recommend going with `.config`.

**Comment by msagolj** [comment]
To follow best practices and recommendations I kept the ~ and cfg.json files for 6.5.5 and cloud, while using .config files and no ~ for 6.4.8.

**Review by vladbailescu — APPROVED** [review]

**Pull request merged**
