### PR TITLE
enforce immutability of certain dispatcher files

### LINKED ISSUE #442: Enforce that immutable dispatcher configuration files are not changed
By using a maven enforcer rules like https://maven.apache.org/enforcer/enforcer-rules/requireFileChecksum.html one can easily enforce at build time that certain files are not touched. That would help to ensure that all files listed in https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html and https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/content-delivery/disp-overview.html#file-structure respectively are not modified.

### PR DESCRIPTION
**Pull request by kwin**
Leverage m-enforcer-p with its MD5 rule for that
Contribute python script to generate enforcer rules

This closes #442

## Description

Enforces that certain dispatcher configuration files are not modified

## Related Issue

#442

## Motivation and Context

Although the documentation states that some files are not supposed to be changed, this is not yet enforced.
Enforcing it makes sense, as changes are not that easy to see (e.g. in PRs because the list of config files which are mutable as well as those which are immutable is big)

## How Has This Been Tested?

IT fails in case immutable config is changed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kwin** [comment]
The only question whether you want to drive automation even further by automatically adjusting the enforcer rules with each build of the archetype. This probably requires changing the script from python to Groovy and executing it during the archetype build with https://groovy.github.io/gmaven/groovy-maven-plugin/

**Comment by msagolj** [comment]
@kwin tried to build your PR on a Win 10 and it fails, saying all files have changed:

```
[INFO] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-checksum-of-immutable-files) @ testing-basic.dispatcher.ams ---
[INFO] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFileChecksum failed with message:
[INFO] There have been changes detected in a file which is supposed to be immutable according to https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html: src/conf/httpd.conf
[INFO] [WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireFileChecksum failed with message:
[INFO] There have been changes detected in a file which is supposed to be immutable according to https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html: src/conf.d/available_vhosts/aem_author.vhost
....
```

comparing files shows that they only differ in line separator:
compare

tried all 3 settings for git's `core.autocrlf` : `input`, `true` and `false`, but no luck.

Build passed on a Mac and we compared the checksums, they are the same, here are some of mine :

```
<configuration>
  <rules>
    <!-- rules being inserted by archetype-pre-package.groovy -->
    <requireFileChecksum>
      <file>src/conf/httpd.conf</file>
      <checksum>c61e88b71d5791c80148d772ecb4a8c0</checksum>
      <type>md5</type>
      <message>There have been changes detected in a file which is supposed to be immutable according to https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html: src/conf/httpd.conf</message>
    </requireFileChecksum>
    <requireFileChecksum>
      <file>src/conf.d/available_vhosts/aem_author.vhost</file>
      <checksum>7791304136ab709af5d77992b9cffb95</checksum>
      <type>md5</type>
      <message>There have been changes detected in a file which is supposed to be immutable according to https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html: src/conf.d/available_vhosts/aem_author.vhost</message>
    </requireFileChecksum>
    <requireFileChecksum>
      <file>src/conf.d/available_vhosts/aem_publish.vhost</file>
      <checksum>8cf34066b28dd09d615f469492ee9fef</checksum>
      <type>md5</type>
      <message>There have been changes detected in a file which is supposed to be immutable according to https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html: src/conf.d/available_vhosts/aem_publish.vhost</message>
    </requireFileChecksum>
```

**Comment by kwin** [comment]
Good observation. This is an issue with the archetype plugin. I opened https://issues.apache.org/jira/browse/ARCHETYPE-610 for a fix. WDYT of only enabling the checks for Mac/Unix? That will at least help users on those platforms...
Once archetype allows to set a line ending we can enable Windows as well.

**Comment by kwin** [comment]
I think we can already support Windows by generating two types of enforcer rule sets: One for Mac/Unix and one for Windows. The former will have MD5s for \n and the latter for \r\n. Both inserted in the pom in different conditional sections. Let me try to work on that in the next days.

**Comment by msagolj** [comment]
@kwin ok, thank you for looking into it. If adding support for Win is to cumbersome/complicated, having it for Mac only is already a improvement.

**Comment by kwin** [comment]
@msagolj Please check again now.

**Comment by msagolj** [comment]
@kwin it fails again on windows but now its also failing inside the build , see above build results.

**Comment by msagolj** [comment]
new checksum approach:
window:
```
<file>src/conf/httpd.conf</file>
<checksum>c48971b67c8b7f2ed8d551ed64cafe4c</checksum>
```
nonwindow:
```
<file>src/conf/httpd.conf</file>
<checksum>b6a3184f6c69b0a3334e455eeec12d45</checksum>
```
old checksum approach:
```
<file>src/conf/httpd.conf</file>
<checksum>c61e88b71d5791c80148d772ecb4a8c0</checksum>
```
shoudn't the old approach' md5 at least match the new nonwindow checksum ?

**Comment by kwin** [comment]
I am assuming that some files don't end with a new line which leads to that difference. I will check later today.

**Comment by kwin** [comment]
@msagolj Can you add a Windows build to CircleCI? Worth testing that too!

**Comment by msagolj** [comment]
@kwin Passes in the build now but fails on Windows. It now produces the same md5 for `windows` and `nonwindows`:

nonwindows:
```
<file>src/conf/httpd.conf</file>
<checksum>b6a3184f6c69b0a3334e455eeec12d45</checksum>
<file>src/conf.d/available_vhosts/aem_author.vhost</file>
<checksum>f84df5d0901bc36c1970eaa18e8a7a26</checksum>
...
```
windows:
```
<file>src/conf/httpd.conf</file>
<checksum>b6a3184f6c69b0a3334e455eeec12d45</checksum>
<file>src/conf.d/available_vhosts/aem_author.vhost</file>
<checksum>f84df5d0901bc36c1970eaa18e8a7a26</checksum>
 ...
```

**Comment by kwin** [comment]
I don't have experience with Circle CI but maybe switching to GitHub Actions would make sense nowadays.

**Comment by vladbailescu** [comment]
@kwin , ok, let's try it out. Would something like #495 be ok?

**Review by vladbailescu — APPROVED** [review]

**Comment by vladbailescu** [comment]
Seems to be working ok on all OSes

**Pull request merged**
