### PR TITLE
sync immutable files with dispatcher SDK 2.0.46 + introduce DISABLE_DEFAULT_CACHING variable

### PR DESCRIPTION
**Pull request by krystiannowak**
sync immutable files with dispatcher SDK 2.0.46 + introduce DISABLE_DEFAULT_CACHING variable

## Description
Syncing immutable files from dispatcher SDK 2.0.46 and introducing DISABLE_DEFAULT_CACHING variable (commented out) for further usage.

## Related Issue
#668

## Motivation and Context

Immutable files should not be different between SDK and archetype.

## How Has This Been Tested?

Generating new project from changed archetype:
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=28-SNAPSHOT \
 -D appTitle="Dispatcher config immutability check" \
 -D appId="dispatcher-config-immutability" \
 -D groupId="com.adobe.aem" \
 -D aemVersion=cloud
 ```

Run `bin/validate.sh archetype/dispatcher-config-immutability/dispatcher/src` against generated project successfully (including immutable config files check this time).

## Screenshots (if appropriate):

n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vladbailescu** [comment]
@krystiannowak, is there a way to automate (maybe with a GH action) checking for a new dispatcher SDK release and creating an update PR?

**Comment by vladbailescu** [comment]
Also, could the dispatcher validation be automated (with a github action)?

**Comment by kwin** [comment]
The old immutable list was based on validator 2.0.23 which shipped with all Dispatcher Cloud SDK up to and including 2.0.45. Where can I find the dispatcher SDK 2.0.36, the latest one one in the AEM SDK at https://experience.adobe.com/#/downloads/content/software-distribution/en/aemcloud.html is still 2.0.45. 
I agree with @vladbailescu that an automatic check would be great, for that we would probably need the dispatcher validator in a Maven repo (compare with #564)

**Comment by krystiannowak** [comment]
@vladbailescu So far only AEM SDK API jar is published, but we have also in our backlog the work to make Dispatcher SDK in more automatic way - so far the customers need to download it from [Software Distribution](https://experience.adobe.com/#/downloads/content/software-distribution/en/aemcloud.html) by themselves.

Dispatcher validator is native, should work just out of the box from Dispatcher SDK, so could be probably quite easy run via GH action. Full validation with the `validate.sh` wrapper required the whole Dispatcher SDK and local Docker system running, as both `httpd -t` step and immutable files checks are done from with Docker - that would require means to run Docker container via GH action (maybe it can be somehow delegated externally).

**Comment by krystiannowak** [comment]
@kwin The list is still the same, just its content slightly changed so that customers see what exactly the files would be (anyway) replaced with and their local environment is even closer to what happens in AEM CS. I took the files from to be released 2.0.46 already, so it has the latest changes (as it's not-in-sync anyway, this choice was probably better than 2.0.45).

Automation is really necessary here, yet first step it to keep it in sync (manually this time unfortunately), as we will have even more value and even more information in build pipelines based on it.

**Comment by vladbailescu** [comment]
Created #670 for automating files updates on dispatcher SDK release. @krystiannowak, we will need to either publish the dispatcher SDK on Maven Central or add some Software Distribution credentials as Github secrets and download it from there.

**Review by vladbailescu — APPROVED** [review]

**Review by bpauli — APPROVED** [review]

**Pull request merged**
