### PR TITLE
Allow video formats to be downloadable, in the filters

### PR DESCRIPTION
**Pull request by ravkiran**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by krystiannowak** [comment]
In sync with WKND's contribution in https://github.com/adobe/aem-guides-wknd/pull/259

**Comment by krystiannowak** [comment]
@vladbailescu - it seems like @ravkiran is not on some list and that's why the "Adobe CLA Signed" check is missing?

**Comment by ravkiran** [comment]
@krystiannowak I've signed Adobe CLA with this option selected
image
Is that ok? Or this is failing because, I might have signed after I've issued this PR?
BTW, I'm using my personal id (ravkiran) instead of adobe email id for this account, is that fine with these contributions?

**Comment by ravkiran** [comment]
Adobe CLA is signed now, will close this PR and re-open
cc: @krystiannowak

**Comment by krystiannowak** [comment]
duplicated by #738

**Pull request closed without merging**
