### PR TITLE
CIF-1746 - Create CIF data types for Content Fragment Models

### PR DESCRIPTION
**Pull request by LSantha**
Enable content fragment models by default in generated project for commerce projects.

## Related Issue

CIF-1746

## How Has This Been Tested?

Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by mhaack — COMMENTED** [review]
This is enabling CF support in general. This should not be specific to Commerce projects only.

**Comment by LSantha** [comment]
@mhaack, I enabled Content Fragment Models only for commerce projects because that's were we need it. I'm not sure if it should be enabled generally. Dedicated teams could have enabled it already for the general case if they wanted to do so.

**Comment by mhaack** [comment]
I think Refsquad team should decide here. AEM archetype is used not only for commerce use cases.

**Comment by bpauli** [comment]
+1 for enabling the CF support in general. @LSantha are you going to update your PR? Otherwise we could also merge it and make the required changes afterwards.

**Comment by LSantha** [comment]
I can update the PR.

**Comment by LSantha** [comment]
Done.

**Review by mhaack — APPROVED** [review]

**Pull request merged**
